################################# Basic configuration #########################
# Documentation: https://gohugo.io/getting-started/configuration/#all-configuration-settings
baseURL = "https://www.whosyourlawnguy.com"
title = "Whos Your Lawn Guy"
theme = "airspace-hugo"
# Number of posts per page in list view
paginate = "4"
# Post excerpt length
summaryLength = "30"
# Disabled languages
disableLanguages = []
# Short name to enable Disqus comments
disqusShortname = "" # Get your shortname from here: https://disqus.com/profile/signup/
# Measurement ID (G-XXXXXXX) to enable Google Analytics
googleAnalytics = "G-T344WY27YV"


################################# Output formats ##############################
# Documentation: https://gohugo.io/templates/output-formats/#customizing-output-formats

[outputs]
home = [ "HTML" ]


################################# Markup ######################################
# Documentation: https://gohugo.io/getting-started/configuration-markup

[markup.goldmark.renderer]
# Allow "unsafe" HTML in Markdown
unsafe = true

[markup.tableOfContents]
  startLevel = 2
  endLevel = 6
  ordered = false


################################# Default parameters ##########################
[params]
logo ="/images/lawnguylogo.png"
logo_width = "160px"
# OpenGraph / Twitter Card metadata
title = "Whos Your Lawn Guy"
description = "Experts in residential lawncare. Located in Southern Indiana, WhosYourLawnGuy services residential properties in surrounding areas."
author = "JE"
images = [ "/images/lawnguylogo.png" ] # First image here will be used as fallback if a page has no images of its own


################################# Sidebar widgets #############################
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]


################################# Contact page ################################
[params.contact]
# Address block
phone = "(502)242-8255"
email = "WhosYourLawnGuy@gmail.com"
location = """
Southern Indiana
"""
# Whether to display text descriptors (like "E-mail: ", "Phone: ") before the address block elements
address_descriptors = true
[params.contact.form]
enable = true
# Whether to use [Netlify Forms](https://docs.netlify.com/forms/setup/)
use_netlify = false
# Form action
## Fill in your Form ID URL for Formspree.io, e.g. `https://formspree.io/f/{form_id}`
## Ignored if `use_netlify = true` (custom [success page](https://docs.netlify.com/forms/setup/#success-messages) is already included) 
action = "https://formspree.io/f/meqveraq"
method = "POST"
# Image on custom success page `/message_sent.html`
success_image = "images/paper-plane.svg"


################################# Google map ##################################
[params.gmap]
enable = true
gmap_api = "2ddd614e6495d2f12c99d4246168c23f03e7b049"
map_latitude = "38.31218"
map_longitude = "-85.80290"
map_marker = ""




################################# Cookies #####################################
[params.cookies]
enable = true
expire_days = 2


################################# Social Media ################################

[[params.social]]
icon = "ion-social-linkedin-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "#"


[[params.social]]
icon = "ion-social-facebook-outline" #ionicon pack v2 : https://ionicons.com/v2/
link = "https://www.facebook.com/whosyourlawnguy/"


################################# Plugins #####################################
# CSS Plugins
[[params.plugins.css]]
link = "plugins/bootstrap/css/bootstrap.min.css"
attributes = "media='screen'"

[[params.plugins.css]]
link = "plugins/ionicons/css/ionicons.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.min.css"
attributes = ""

[[params.plugins.css]]
link = "plugins/slick/slick.css"
attributes = ""

# JS Plugins
[[params.plugins.js]]
link = "plugins/jquery/jquery.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/bootstrap/js/bootstrap.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/magnific-popup/magnific-popup.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
attributes = ""

[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
attributes = "defer"


################################# English translation #########################
[languages.en]
languageName = "English"
languageCode = "en-US"
contentDir = "content/english"
weight = 1
copyright = "Copyright &copy; 2021. Built with 👾 by [almadon.io](https://almadon.io)"

# Main menu
[[languages.en.menu.main]]
name = "Home"
URL = "/"
weight = 1

[[languages.en.menu.main]]
name = "About"
URL = "about"
weight = 2

[[languages.en.menu.main]]
name = "Service"
URL = "service"
weight = 3

[[languages.en.menu.main]]
name = "Contact"
URL = "contact"
weight = 4

# Footer menu
[[languages.en.menu.footer]]
name = "About"
URL = "about"
weight = 1

[[languages.en.menu.footer]]
name = "Service"
URL = "service"
weight = 2


[[languages.en.menu.footer]]
name = "Contact"
URL = "contact"
weight = 3

